version: "3.3"
services:
  proj1:    
    container_name: proj1
    build:      
      context: .
      dockerfile: proj1/Dockerfile
    depends_on: [ mssql ]        
    ports:
      - "8080:80"
  proj2:
    container_name: proj2
    build:
      context: .
      dockerfile: proj2/Dockerfile
    ports:
      - "8081:80"

  mssql:
    image: "mcr.microsoft.com/mssql/server"
    container_name: mssql
    hostname: mssql
    environment:
      SA_PASSWORD: "Pass123!"
      ACCEPT_EULA: "Y"
    restart: unless-stopped    
    ports:
      # So we can access the database
      # From a tool like JetBrains Rider
      # Optional for this demo
      - "11433:1433" 